"""AI extraction (Gemini, file-friendly) + reasoning/insights (GPT-5.2).

Architecture note:
- Invoice files (PDF/PNG/JPG) are passed to Gemini 3 Flash through emergentintegrations'
  FileContentWithMimeType, since that's the supported path for file attachments.
- The reasoning/explainability layer ("WHY did the AI flag this?") and the dashboard
  insights are generated by GPT-5.2 as requested by the user.
"""
from __future__ import annotations

import json
import logging
import os
import re
from typing import Any, Dict, List

try:
    from emergentintegrations.llm.chat import (
        LlmChat, UserMessage, FileContentWithMimeType,
    )
    _LLM_AVAILABLE = True
except ImportError:
    _LLM_AVAILABLE = False
    logging.getLogger(__name__).warning(
        "emergentintegrations not installed — AI extraction/insights are disabled. "
        "This is expected in local dev; wire up a direct provider SDK before production."
    )

logger = logging.getLogger(__name__)

EMERGENT_KEY = os.environ.get("EMERGENT_LLM_KEY", "")

EXTRACTION_SYSTEM_PROMPT = """You are an OCR + structured-extraction engine for an Indian influencer marketing agency.
Read the uploaded creator invoice (PDF or image) and return a SINGLE JSON object with EXACTLY these keys (no markdown, no commentary):

{
  "creator_name": str,
  "invoice_number": str,
  "invoice_date": str,           // ISO YYYY-MM-DD if possible, else raw string
  "campaign_reference": str,     // any campaign / brand / project reference
  "gross_amount": float,         // pre-tax invoice total in INR
  "gst_amount": float,           // 0 if not present
  "pan": str,                    // empty string if not present
  "gstin": str,                  // empty string if not present
  "bank_name": str,
  "account_number": str,
  "ifsc": str,
  "upi_id": str,
  "deliverables": str,           // short comma-separated list
  "invoice_notes": str,          // any extra notes from the invoice
  "line_items": [ {"description": str, "quantity": int, "rate": float, "amount": float} ],
  "confidence_score": float      // 0..1 self-rated overall confidence
}

Rules:
- Output PURE JSON, no markdown fences.
- Use empty string "" for any missing text field; 0 for missing numbers.
- All amounts in INR (no currency symbol)."""


REASONING_SYSTEM_PROMPT = """You are a finance copilot for an Indian influencer-marketing agency.
You will be given a list of detected anomalies on a single creator invoice.
For each anomaly, return one short, natural sentence (max 22 words) starting with the WHY — comparing actual vs expected. Be specific with numbers and reference the campaign sheet. Do NOT use markdown."""


INSIGHTS_SYSTEM_PROMPT = """You are a finance copilot. Given a JSON summary of an agency's monthly invoice run,
produce 4-6 sharp 'AI insight cards' as a JSON array with this shape:

[
  {"title": str, "body": str, "severity": "critical"|"warning"|"info"|"success", "amount": float|null, "icon": "alert-triangle"|"banknote"|"sparkles"|"shield-check"|"trending-up"|"copy"|"id-card"}
]

Rules:
- 1 sentence body, max 22 words.
- Reference real numbers from the input.
- Output PURE JSON array, no markdown."""


def _strip_json(text: str) -> str:
    """Remove markdown fences from a JSON-ish LLM response."""
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    return text.strip()


async def extract_invoice_from_file(file_path: str, mime_type: str) -> Dict[str, Any]:
    """Run Gemini 3 Flash to extract a structured invoice JSON from a file."""
    if not _LLM_AVAILABLE:
        raise RuntimeError(
            "AI extraction is unavailable: emergentintegrations is not installed. "
            "Install it (private package) or wire up a direct provider SDK."
        )
    if not EMERGENT_KEY:
        raise RuntimeError("EMERGENT_LLM_KEY not configured")

    session_id = f"extract-{os.path.basename(file_path)}"
    chat = LlmChat(
        api_key=EMERGENT_KEY,
        session_id=session_id,
        system_message=EXTRACTION_SYSTEM_PROMPT,
    ).with_model("gemini", "gemini-2.5-flash")

    file_obj = FileContentWithMimeType(file_path=file_path, mime_type=mime_type)
    msg = UserMessage(
        text="Extract the invoice fields from the attached document. Return ONLY the JSON object described in the system prompt.",
        file_contents=[file_obj],
    )
    response = await chat.send_message(msg)
    text = _strip_json(str(response))
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        # try to find the first JSON object in the response
        m = re.search(r"\{.*\}", text, flags=re.S)
        if not m:
            raise
        data = json.loads(m.group(0))
    return data


async def gpt52_explain_anomalies(invoice: Dict[str, Any], anomalies: List[Dict[str, Any]],
                                  campaign: Dict[str, Any] | None) -> List[str]:
    """Ask GPT-5.2 to write the human-readable 'reason' for each anomaly."""
    if not EMERGENT_KEY or not anomalies:
        return [a.get("reason", "") for a in anomalies]
    chat = LlmChat(
        api_key=EMERGENT_KEY,
        session_id=f"explain-{invoice.get('id', 'inv')}",
        system_message=REASONING_SYSTEM_PROMPT,
    ).with_model("openai", "gpt-5.2")

    payload = {
        "invoice": {k: invoice.get(k) for k in (
            "creator_name", "invoice_number", "gross_amount", "gst_amount",
            "pan", "gstin", "bank_name", "account_number", "ifsc", "campaign_reference"
        )},
        "campaign": campaign,
        "anomalies": [{"code": a.get("code"), "label": a.get("label"),
                       "expected": a.get("expected"), "actual": a.get("actual")} for a in anomalies],
    }
    msg = UserMessage(
        text="Anomalies:\n" + json.dumps(payload, default=str) +
        "\n\nReturn a JSON array of strings, same length and order as 'anomalies', each string being the one-sentence reason. Output ONLY the JSON array.",
    )
    try:
        response = await chat.send_message(msg)
        text = _strip_json(str(response))
        reasons = json.loads(text)
        if isinstance(reasons, list) and len(reasons) == len(anomalies):
            return [str(r) for r in reasons]
    except Exception as e:
        logger.warning("GPT-5.2 explain failed: %s", e)
    return [a.get("reason", "") for a in anomalies]


async def gpt52_dashboard_insights(summary: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Generate 4-6 AI insight cards for the dashboard."""
    if not EMERGENT_KEY:
        return []
    chat = LlmChat(
        api_key=EMERGENT_KEY,
        session_id=f"insights-{summary.get('user_id', 'u')}",
        system_message=INSIGHTS_SYSTEM_PROMPT,
    ).with_model("openai", "gpt-5.2")
    msg = UserMessage(text=json.dumps(summary, default=str))
    try:
        response = await chat.send_message(msg)
        text = _strip_json(str(response))
        cards = json.loads(text)
        if isinstance(cards, list):
            return cards
    except Exception as e:
        logger.warning("GPT-5.2 insights failed: %s", e)
    return []
